{{- if eq .Values.hostPath "pvc" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nsm-spire-agent-socket
    namespace: {{ .Release.Namespace }}
spec:
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    selector:
      matchLabels:
        hostpath: nsm-spire-agent-socket
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nsm-spiffe-csi-socket-dir
    namespace: {{ .Release.Namespace }}
spec:
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    selector:
      matchLabels:
        hostpath: nsm-spiffe-csi-socket-dir
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nsm-mountpoint-dir
    namespace: {{ .Release.Namespace }}
spec:
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    selector:
      matchLabels:
        hostpath: nsm-mountpoint-dir
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nsm-kubelet-plugin-registration-dir
    namespace: {{ .Release.Namespace }}
spec:
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    selector:
      matchLabels:
        hostpath: nsm-kubelet-plugin-registration-dir
{{- end }}
