{{- if eq .Values.hostPath "pvc" }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: nsm-spire-agent-socket
    labels:
      hostpath: nsm-spire-agent-socket
spec:
    storageClassName: manual
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
      path: "/run/spire/sockets"
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: nsm-spiffe-csi-socket-dir
    labels:
      hostpath: nsm-spiffe-csi-socket-dir
spec:
    storageClassName: manual
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
      path: "/var/lib/kubelet/plugins/csi.spiffe.io"
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: nsm-mountpoint-dir
    labels:
      hostpath: nsm-mountpoint-dir
spec:
    storageClassName: manual
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
      path: "/var/lib/kubelet/pods"
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: nsm-kubelet-plugin-registration-dir
    labels:
      hostpath: nsm-kubelet-plugin-registration-dir
spec:
    storageClassName: manual
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
      path: "/var/lib/kubelet/plugins_registry"
{{- end }}
